// Real Philippine pickleball courts (crowd-sourced from public Google listings,
// geocoded via OpenStreetMap). Seeded as unverified, pending review. See docs/10.
export interface SeedCourt {
  name: string;
  lat: number;
  lng: number;
  address: string;
  city: string;
  country: string;
  hasLighting: boolean;
  phone: string | null;
  website: string | null;
}

export const PH_COURTS: SeedCourt[] = [
  {
    name: "Wrong House Pickleball Court",
    lat: 11.005116,
    lng: 124.602292,
    address: "Purok 4, Brgy. Simangan, Ormoc City, 6541 Leyte",
    city: "Ormoc City",
    country: "Philippines",
    hasLighting: false,
    phone: "0999 883 1170",
    website: "https://www.facebook.com/profile.php?id=61573153073914",
  },
  {
    name: "Ace Pickleball Hub",
    lat: 11.001444,
    lng: 124.606216,
    address: "Pag-ibig Subd, Ormoc City, 6541 Leyte",
    city: "Ormoc City",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 688 8874",
    website: null,
  },
  {
    name: "ServNdink Pickleball Court",
    lat: 11.068087,
    lng: 124.377987,
    address: "Sitio Bituon, San Juan, Palompon, 6538 Leyte",
    city: "Palompon",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Waypoint Pickleball Court",
    lat: 11.1045,
    lng: 124.4008,
    address: "Lomonon, Palompon, Leyte",
    city: "Palompon",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/share/14Rk5HptvtG/",
  },
  {
    name: "Smash Zone",
    lat: 11.242348,
    lng: 124.999928,
    address: "6245+2CG Tabuan National Hwy, Tacloban City, Leyte",
    city: "Tacloban City",
    country: "Philippines",
    hasLighting: false,
    phone: "0956 316 6359",
    website: "https://www.supersaas.com/schedule/SmashZoneTac/Pickleball",
  },
  {
    name: "Pampanga Pickleball Center",
    lat: 15.114283,
    lng: 120.608872,
    address: "Lot 2, Warehouse 1, Brgy. Telabastagan, San Fernando, 2000 Pampanga",
    city: "San Fernando",
    country: "Philippines",
    hasLighting: false,
    phone: "0908 989 2323",
    website: "https://pampanga-pickleball.rezerv.co/",
  },
  {
    name: "The Courtside Cebu",
    lat: 10.243608,
    lng: 123.844792,
    address: "N. Bacalso Ave, Starmall Talisay, 6045 Cebu",
    city: "Talisay",
    country: "Philippines",
    hasLighting: false,
    phone: "0930 392 0719",
    website: "https://thecourtsidecebu.com/",
  },
  {
    name: "The Pickle Yard Parañaque",
    lat: 14.490818,
    lng: 121.04337,
    address: "Km 15 West Service Road, SLEX, Parañaque, 1709 Metro Manila",
    city: "Parañaque",
    country: "Philippines",
    hasLighting: false,
    phone: "0936 959 5004",
    website: "https://www.facebook.com/profile.php?id=61567306075454",
  },
  {
    name: "24/7 Pickle Mandaluyong",
    lat: 14.578089,
    lng: 121.038922,
    address: "362 San Rafael St, Mandaluyong City, Metro Manila",
    city: "Mandaluyong City",
    country: "Philippines",
    hasLighting: true,
    phone: "0936 949 0815",
    website: "https://reclub.co/clubs/@24-7-pickle-mandaluyong",
  },
  {
    name: "Neopolitan Brittany Pickleball Courts",
    lat: 14.724751,
    lng: 121.054783,
    address: "Neopolitan Ave, Quezon City, Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: true,
    phone: "(02) 8461 3534",
    website: null,
  },
  {
    name: "Pickle Play",
    lat: 14.169878,
    lng: 120.921828,
    address: "Emerald 1, Crisanto M. De Los Reyes Ave, Amadeo, Cavite",
    city: "Amadeo",
    country: "Philippines",
    hasLighting: false,
    phone: "0927 355 8909",
    website: "https://facebook.com/pickleplayph",
  },
  {
    name: "Tierra Pickleball Club",
    lat: 14.674985,
    lng: 121.053448,
    address: "Tierra Verde, 2 Kalaw Ledesma Cir, Quezon City, 1116 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "0969 085 7204",
    website: "https://www.facebook.com/tierrapickleball",
  },
  {
    name: "Pickleball Central PH",
    lat: 15.134763,
    lng: 120.56727,
    address: "Fil-Am Friendship Hwy, Angeles, 2009 Pampanga",
    city: "Angeles",
    country: "Philippines",
    hasLighting: false,
    phone: "0908 891 1206",
    website: null,
  },
  {
    name: "Zone Sports Center",
    lat: 14.549852,
    lng: 121.030256,
    address: "7224 Sen. Gil J. Puyat Ave, Makati City, Metro Manila",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: "0945 204 3013",
    website: "https://bit.ly/thezoneph",
  },
  {
    name: "PEDCI Pickleball Courts",
    lat: 14.583986,
    lng: 121.112543,
    address: "Village East Executive Homes, Sto. Domingo, Cainta, 1900 Rizal",
    city: "Cainta",
    country: "Philippines",
    hasLighting: true,
    phone: "0927 450 5978",
    website: "https://www.facebook.com/share/N1DMpYRhsNCpR55G/",
  },
  {
    name: "PickleballHub",
    lat: 14.422706,
    lng: 121.042081,
    address: "Km. 21 West Service Rd, Muntinlupa, Metro Manila",
    city: "Muntinlupa",
    country: "Philippines",
    hasLighting: false,
    phone: "0968 207 8876",
    website: "https://pickleballhubph.playbypoint.com/",
  },
  {
    name: "Davao Pickleball Court (Matina Town Square)",
    lat: 7.063788,
    lng: 125.596625,
    address: "Matina Town Square, Gen. Douglas MacArthur Hwy, Matina, Davao City",
    city: "Davao City",
    country: "Philippines",
    hasLighting: false,
    phone: "(082) 297 1780",
    website: "https://jfmdevelopmentcorp.com/pickleball",
  },
  {
    name: "Manila Pickleball Club (MPC)",
    lat: 14.570039,
    lng: 120.991526,
    address: "Malate, Manila, Metro Manila",
    city: "Manila",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/share/g/12BufEeWdwP/",
  },
  {
    name: "Powerhouse Pickleball and Badminton Center",
    lat: 14.250247,
    lng: 120.975527,
    address: "Km 39 Emilio Aguinaldo Hwy, Biga, Silang, 4118 Cavite",
    city: "Silang",
    country: "Philippines",
    hasLighting: true,
    phone: "0916 634 7024",
    website: "https://www.facebook.com/share/1BosxYBzoS/",
  },
  {
    name: "Green Kitchen Pickleball Tarlac",
    lat: 15.482926,
    lng: 120.619422,
    address: "Sunrise Subdivision, Camella Access Rd, Maliwalo, Tarlac City",
    city: "Maliwalo",
    country: "Philippines",
    hasLighting: false,
    phone: "0945 879 0478",
    website: null,
  },
  {
    name: "Masey Pickleball Boracay",
    lat: 11.978874,
    lng: 121.920293,
    address: "Citymall Boracay, Malay, 5608 Aklan",
    city: "Malay",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 163 9399",
    website: "https://www.instagram.com/maseypickleballboracay?igsh=dGc3eHVoZHV0czlw",
  },
  {
    name: "Courtwoods Pickleball Court",
    lat: 9.627208,
    lng: 123.878822,
    address: "157 Espuelas Street, Tagbilaran City, 6300 Bohol",
    city: "Tagbilaran City",
    country: "Philippines",
    hasLighting: false,
    phone: "0945 366 1609",
    website: null,
  },
  {
    name: "Pickleball Central Tarlac",
    lat: 15.486122,
    lng: 120.589347,
    address: "GJ72 4RQ Pickleball Central Tarlac, Tarlac City, Tarlac",
    city: "Tarlac City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Pickleball Court SM Sta. Mesa",
    lat: 14.651055,
    lng: 121.048625,
    address: "Roof Deck, SM City, Aurora Blvd, Santa Mesa, Quezon City, Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/SMCityStaMesa/",
  },
  {
    name: "Match Point - Badminton and Pickleball Court",
    lat: 10.399849,
    lng: 123.998762,
    address: "92V2 2FC Match Point - Badminton and Pickleball Court, Liloan, Cebu",
    city: "Liloan",
    country: "Philippines",
    hasLighting: false,
    phone: "0947 884 0746",
    website: "https://www.instagram.com/matchpoint.cebu?igsh=cmI2NjNnZ3h4d2M5",
  },
  {
    name: "Pickle 8",
    lat: 9.310845,
    lng: 123.276653,
    address: "Dumaguete - Palinpinon Rd., Dumaguete City, 6200 Negros Oriental",
    city: "Dumaguete City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://pickle8.site/",
  },
  {
    name: "City of Naga Pickleball Court",
    lat: 10.208472,
    lng: 123.759096,
    address: "6Q56 267 City of Naga Pickleball Court, East Poblacion, Naga, Cebu",
    city: "Naga",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Activate One Ayala",
    lat: 14.556795,
    lng: 121.021123,
    address: "Level 5, Activate One Ayala, Ayala Malls One Ayala, Makati City, Metro Manila",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: "0915 091 6858",
    website: "https://activatesportsph.rezerv.co/?fbclid=IwY2xjawJHoB9leHRuA2FlbQIxMAABHSjECRFjtxXixh9c86mZotVgkAYrShApxHyxxbCE1IaUvyl1uVOk2Vm1qg_aem_f-YHEAhhIAmYMTD9Iuo2ng",
  },
  {
    name: "Gameville Double Play",
    lat: 14.560517,
    lng: 121.076434,
    address: "St., Villa Miguela, 104 S Reyes, Pasig, 1602 Metro Manila",
    city: "Pasig",
    country: "Philippines",
    hasLighting: false,
    phone: "0932 208 6138",
    website: "https://www.venyu.ph/venue/gameville-double-play",
  },
  {
    name: "Amadea Resort and Pickleball",
    lat: 14.169801,
    lng: 120.918936,
    address: "4560 BARANGAY 12, Amadeo, Cavite",
    city: "Amadeo",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Magnum Sports Complex",
    lat: 10.328561,
    lng: 123.900885,
    address: "8WM4 JWV Magnum Sports Complex, San Miguel Rd, Apas, Cebu City, 6000 Cebu",
    city: "Cebu City",
    country: "Philippines",
    hasLighting: false,
    phone: "0915 461 2097",
    website: "https://magnumsportscomplex.com/",
  },
  {
    name: "Greenhills West Club House",
    lat: 14.600192,
    lng: 121.042034,
    address: "21 Roosevelt, San Juan City, 1500 Metro Manila",
    city: "San Juan City",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 531 2254",
    website: null,
  },
  {
    name: "PCKLPARK CDO",
    lat: 8.486071,
    lng: 124.656805,
    address: "FMV2 FPF PCKLPARK CDO, Julio Pacana Street, Cagayan De Oro City, Misamis Oriental",
    city: "Cagayan De Oro City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "John Hay Sports Pavilion",
    lat: 16.432957,
    lng: 120.651501,
    address: "9JX5 CW4 John Hay Sports Pavilion, Ordonio Dr, Camp John Hay, Baguio, Benguet",
    city: "Baguio",
    country: "Philippines",
    hasLighting: false,
    phone: "0995 647 2323",
    website: "http://www.johnhaysportspavilion.com/",
  },
  {
    name: "Pickleball Society",
    lat: 10.282124,
    lng: 124.785863,
    address: "Matalom, Leyte",
    city: "Matalom",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "The Smash City",
    lat: 14.69169,
    lng: 120.969453,
    address: "30 F. Alarcon Street, Maysan Rd, Valenzuela, 1440 Metro Manila",
    city: "Valenzuela",
    country: "Philippines",
    hasLighting: false,
    phone: "0962 935 4912",
    website: "https://thesmashcity.com/",
  },
  {
    name: "Greenmeadows I Pickleball Court",
    lat: 14.595931,
    lng: 121.076985,
    address: "24 Warbler St, Quezon City, 1110 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Manila Bulletin Gym",
    lat: 14.590449,
    lng: 120.980362,
    address: "HXQH 27P Manila Bulletin Gym, Muralla Street, corner Recoletos Street, Intramuros, Metro Manila, Manila, 1002",
    city: "Manila",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8527 8121",
    website: "http://www.mb.com.ph/",
  },
  {
    name: "Panda Pickleball Center",
    lat: 14.363943,
    lng: 121.056771,
    address: "Southgate Warehouse Complex, Warehouse 2 Narra Rd, San Antonio, San Pedro, 4023 Laguna",
    city: "San Pedro",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "BSF Pickleball Court",
    lat: 10.323516,
    lng: 124.791113,
    address: "Bato School of Fisheries, Bato, Leyte",
    city: "Bato",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "SweetSpot pickleball courts CEBU",
    lat: 10.327418,
    lng: 123.942152,
    address: "HVG IT Park, Mandaue, Cebu",
    city: "Mandaue",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Hangar Pickleball Club",
    lat: 10.316685,
    lng: 123.890995,
    address: "Hangar, Back Gate - Deca 4, General Aviation Rd, Lapu-Lapu, 6015 Cebu",
    city: "Lapu-Lapu",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Hermongreens Pickleball Court",
    lat: 10.677802,
    lng: 124.797753,
    address: "PQQV P9R Hermongreens Pickleball Court, City of Baybay, Leyte",
    city: "City of Baybay",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Standout Pickleball ARENA Blue Ridge B",
    lat: 14.651055,
    lng: 121.048625,
    address: "Starline, 32 Starline Road, Project 4, Quezon City, 1109 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 776 0909",
    website: "https://www.facebook.com/share/1A1gPCwZSX/?mibextid=wwXIfr",
  },
  {
    name: "Camotes Pickleball Club",
    lat: 10.645918,
    lng: 124.381768,
    address: "San Francisco, Cebu",
    city: "San Francisco",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Beach Placid Pickleball Court",
    lat: 11.153795,
    lng: 123.806863,
    address: "5R93 G7J Beach Placid Pickleball Court, Santa Fe, Cebu",
    city: "Santa Fe",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Pickleball HQ",
    lat: 14.338826,
    lng: 121.084183,
    address: "73W4 978 Pickleball HQ, Carmona - Timbao Rd, Biñan, Laguna",
    city: "Biñan",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Iloilo Pickleball",
    lat: 10.736291,
    lng: 122.545701,
    address: "Lopez Jaena St, Jaro, Iloilo City, 5000",
    city: "Iloilo City",
    country: "Philippines",
    hasLighting: false,
    phone: "0928 339 3188",
    website: null,
  },
  {
    name: "IT Park Pickleball Court",
    lat: 10.328561,
    lng: 123.900885,
    address: "8WM5 PV6 IT Park Pickleball Court, Apas, Cebu City, 6000 Cebu",
    city: "Cebu City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Westside Pickleball",
    lat: 10.677802,
    lng: 124.797753,
    address: "MRP5 5J2 Westside Pickleball, City of Baybay, Leyte",
    city: "City of Baybay",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Picklepals",
    lat: 6.116951,
    lng: 125.171543,
    address: "San Miguel St, General Santos City (Dadiangas), 9500 South Cotabato",
    city: "General Santos City (Dadiangas)",
    country: "Philippines",
    hasLighting: false,
    phone: "0993 807 9808",
    website: "https://picklepals.co/",
  },
  {
    name: "PickleTown - Davao",
    lat: 7.106626,
    lng: 125.629504,
    address: "Warehouse A1, PickleTown - Davao, Carmelite Rd, Belisario, Davao City",
    city: "Belisario",
    country: "Philippines",
    hasLighting: false,
    phone: "0927 725 8015",
    website: null,
  },
  {
    name: "Ground Game - Pickleball / Basketball / Badminton Court",
    lat: 14.616476,
    lng: 121.005372,
    address: "25 Data, Quezon City, 1113 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "0962 554 5953",
    website: "https://www.facebook.com/profile.php?id=61560811344860",
  },
  {
    name: "OH! Pickleball Court",
    lat: 14.577439,
    lng: 121.033897,
    address: "16 San Rafael Ext, Plainview, Mandaluyong City, 1550 Metro Manila",
    city: "Mandaluyong City",
    country: "Philippines",
    hasLighting: false,
    phone: "0920 135 4961",
    website: "https://ohpc.rezerv.co/appointment-booking?apptId=abfd94cf-5a56-4849-a636-4de2e76a2b72&locationId=67241348-50b5-4eb9-8a98-41c305e03fcc&durationId=723f3dac-3da3-4a45-9848-ed15403dd87b",
  },
  {
    name: "Angeles Pickleball Center",
    lat: 15.174747,
    lng: 120.587947,
    address: "MacArthur Hwy, Angeles, Pampanga",
    city: "Angeles",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/profile.php?id=61563543320714",
  },
  {
    name: "Palms pickleball court",
    lat: 14.556795,
    lng: 121.021123,
    address: "1401 P.Ocampo St., San Andres Bukid, Makati City, Metro Manila",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "BACOLOD PICKLEBALL HQ",
    lat: 10.6767,
    lng: 122.9563,
    address: "Lopez Jaena, Hernaez St, Bacolod City, Negros Occidental",
    city: "Bacolod City",
    country: "Philippines",
    hasLighting: false,
    phone: "0908 885 3555",
    website: "https://www.facebook.com/bacolodpickleball?mibextid=ZbWKwL",
  },
  {
    name: "Pickleball Hub at Tiendesitas",
    lat: 14.560517,
    lng: 121.076434,
    address: "Level 2 Bldg. A, Tiendesitas Ortiges, East Eulogio Rodriguez Jr. Ave, Pasig, 1604 Metro Manila",
    city: "Pasig",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://picklehub-court-reservation.vercel.app/",
  },
  {
    name: "Revel Grove",
    lat: 14.314604,
    lng: 121.1137,
    address: "Area 1, Revel Grove, Filsyn Compound, W13, City of Santa Rosa, 4026 Laguna",
    city: "City of Santa Rosa",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/revelgrove/",
  },
  {
    name: "The Pickle Yard Dasmariñas",
    lat: 14.327082,
    lng: 120.937087,
    address: "7XV9 3RG The Pickle Yard Dasmariñas, AON Warehouse, Governor's Dr, Sampaloc Uno, Dasmariñas, Cavite",
    city: "Dasmariñas",
    country: "Philippines",
    hasLighting: false,
    phone: "0998 558 1294",
    website: "https://www.facebook.com/profile.php?id=61575648282287#",
  },
  {
    name: "Hemady Sports Plaza",
    lat: 14.614075,
    lng: 121.037551,
    address: "9 Doña Hemady St, Valencia, Quezon City, 1112 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8726 6351",
    website: null,
  },
  {
    name: "Bacnotan Pickleball Club",
    lat: 16.720256,
    lng: 120.352594,
    address: "Guerrero Ave, Nagsaraboan, Bacnotan, 2515 La Union",
    city: "Bacnotan",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 188 3164",
    website: null,
  },
  {
    name: "Veterans Memorial Medical Center Upper House Tennis and Pickleball Club",
    lat: 14.651055,
    lng: 121.048625,
    address: "M25Q P4M Veterans Memorial Medical Center Upper House Tennis and Pickleball Club, 173, Quezon City, 1100 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8926 1315",
    website: null,
  },
  {
    name: "The 3rd Shot Homecourt",
    lat: 14.556795,
    lng: 121.021123,
    address: "1238 Gen. Jacinto St, Makati City, Metro Manila",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.playkorte.com/facilities/the-3rd-shot-19cdc34c1aa",
  },
  {
    name: "ALPHA & OMEGA PICKLEBALL",
    lat: 14.338826,
    lng: 121.084183,
    address: "Warehouse Corporate Park, Santo Tomas Rd, Biñan, 4024 Laguna",
    city: "Biñan",
    country: "Philippines",
    hasLighting: false,
    phone: "0977 855 0789",
    website: "http://www.alphaandomegapickleball.com/",
  },
  {
    name: "SideOut Pickleball Court",
    lat: 10.529364,
    lng: 124.022624,
    address: "St Peter Village Street, Danao, Cebu",
    city: "Danao",
    country: "Philippines",
    hasLighting: false,
    phone: "0906 081 0205",
    website: null,
  },
  {
    name: "RCCV PICKLEBALL COURT",
    lat: 11.155222,
    lng: 123.808243,
    address: "200 F. Roska Street, Santa Fe, 6045 Cebu",
    city: "Santa Fe",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Burn Room Pickleball",
    lat: 9.30428,
    lng: 123.3068,
    address: "77M7 775, Road Talay Dumaguete CityNegros Oriental, 6200 Negros Oriental",
    city: "Road Talay Dumaguete CityNegros Oriental",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "PickleBohol (Pickleball Court)",
    lat: 9.740931,
    lng: 123.84297,
    address: "PRVR 7X3 PickleBohol (Pickleball Court), Barnido St, Maribojoc, Bohol",
    city: "Maribojoc",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/groups/281360938092149/?ref=share_group_link",
  },
  {
    name: "Picklewin Pickleball Court",
    lat: 11.296208,
    lng: 123.732926,
    address: "Burgos, Mancilang, Madridejos, 6053 Cebu",
    city: "Madridejos",
    country: "Philippines",
    hasLighting: false,
    phone: "0942 306 3072",
    website: null,
  },
  {
    name: "Plaza Asuncion Covered Court",
    lat: 14.590449,
    lng: 120.980362,
    address: "HX8Q PPF Plaza Asuncion Covered Court, Quirino Ave, Malate, Manila, 1004 Metro Manila",
    city: "Manila",
    country: "Philippines",
    hasLighting: false,
    phone: "0910 218 5942",
    website: null,
  },
  {
    name: "Bounce at Parqal- Basketball, Volleyball & Pickleball Courts",
    lat: 14.500812,
    lng: 120.991533,
    address: "Ground Floor, Bounce at Parqal- Basketball, Volleyball & Pickleball Courts, Parqal Mall, Parañaque, Metro Manila",
    city: "Parañaque",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 100 7670",
    website: "https://bounceatparqal.com/",
  },
  {
    name: "DragonSmash - Taguig",
    lat: 14.527054,
    lng: 121.074494,
    address: "G3QG 36P DragonSmash - Taguig, Pedro Cayetano Blvd, Taguig, Metro Manila",
    city: "Taguig",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 182 0580",
    website: "http://www.dragonsmashph.com/",
  },
  {
    name: "Court 463",
    lat: 14.617774,
    lng: 121.00233,
    address: "463 E Rodriguez Sr. Ave, Quezon City, Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "0926 683 2427",
    website: null,
  },
  {
    name: "ML Lifestyle Park - Sports & Food Park",
    lat: 10.328561,
    lng: 123.900885,
    address: "Barangay San Jose Road, Cebu City, 6000 Cebu",
    city: "Cebu City",
    country: "Philippines",
    hasLighting: false,
    phone: "0939 784 2901",
    website: "http://webpos.lavielifestyle.ph/public/availability/",
  },
  {
    name: "PALAWAN PADEL CLUB",
    lat: 11.180039,
    lng: 119.390496,
    address: "Vanilla beach bgy Korong-korong, El Nido, 5313 Palawan",
    city: "El Nido",
    country: "Philippines",
    hasLighting: false,
    phone: "0968 526 6171",
    website: "https://palawanpadelclub.setmore.com/beta",
  },
  {
    name: "POK! Pickleball Courts",
    lat: 9.305478,
    lng: 123.308045,
    address: "Purok Mahusay, Dumaguete City, 6200 Negros Oriental",
    city: "Dumaguete City",
    country: "Philippines",
    hasLighting: true,
    phone: null,
    website: "https://app.court-access.com/facility/27122156-6722-4c24-b4ba-d090de6c04ec",
  },
  {
    name: "Twinville Civic Center",
    lat: 14.650191,
    lng: 121.090291,
    address: "45 Camia St, Marikina, 1800 Metro Manila",
    city: "Marikina",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Plaridel Pickleball Court",
    lat: 10.677802,
    lng: 124.797753,
    address: "HQ77 GRV Plaridel Pickleball Court, City of Baybay, Leyte",
    city: "City of Baybay",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Village Sports Club",
    lat: 14.500812,
    lng: 120.991533,
    address: "BF Homes, El Grande, corner Tropical Ave, Parañaque, 1747 Metro Manila",
    city: "Parañaque",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8822 1000",
    website: "http://vsportsclub.com/",
  },
  {
    name: "The City Club",
    lat: 14.556795,
    lng: 121.021123,
    address: "4F, The City Club, 7232 Ayala Ave, Extension, Makati City, 1209 Metro Manila",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8737 0000",
    website: "http://www.cityclub.com.ph/",
  },
  {
    name: "Sogod Pickleball Community",
    lat: 10.384588,
    lng: 124.980803,
    address: "9XQM HVX Sogod Pickleball Community, Zone V, Pob, Sogod, Southern Leyte",
    city: "Sogod",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Makati Sports Club",
    lat: 14.556795,
    lng: 121.021123,
    address: "Gallardo Streets, Salcedo Village, L.P. Leviste Street, Makati City, 1227",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8817 8731",
    website: "https://makatisportsclub.com/",
  },
  {
    name: "The Dink Loft",
    lat: 14.633108,
    lng: 121.099354,
    address: "7th St, Mayor Gil Fernando Ave, Marikina, 1800 Metro Manila",
    city: "Marikina",
    country: "Philippines",
    hasLighting: false,
    phone: "0905 558 9982",
    website: "https://www.thedinkloft.com/",
  },
  {
    name: "Pickleplay.ph Banawa Branch",
    lat: 10.328561,
    lng: 123.900885,
    address: "Happy Valley, 1st St, Labangon, Cebu City, 6000 Cebu",
    city: "Cebu City",
    country: "Philippines",
    hasLighting: false,
    phone: "0919 990 9642",
    website: "https://www.pickleplay.ph/",
  },
  {
    name: "Terra Courts Pickleball Space",
    lat: 15.028301,
    lng: 120.693804,
    address: "1st street, Dolores Homesite Ext Rd, Dolores, San Fernando, 2000 Pampanga",
    city: "San Fernando",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "http://terracourts.com/",
  },
  {
    name: "365 Badminton Court(pickleball)",
    lat: 14.5437,
    lng: 120.99465,
    address: "2647-2651 F.B. Harrison Brgy. 76, Naushon Rd, Pasay City, Metro Manila",
    city: "Pasay City",
    country: "Philippines",
    hasLighting: true,
    phone: "0926 710 4893",
    website: null,
  },
  {
    name: "New Manila Rolling Hills Clubhouse",
    lat: 14.651055,
    lng: 121.048625,
    address: "J27C C84 New Manila Rolling Hills Clubhouse, Twin Hills, Mariana, Quezon City, Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "(02) 8240 3907",
    website: null,
  },
  {
    name: "El Nido Pickle Park",
    lat: 11.180039,
    lng: 119.390496,
    address: "Santan Street, El Nido, 5313 Palawan",
    city: "El Nido",
    country: "Philippines",
    hasLighting: false,
    phone: "0967 205 6628",
    website: "https://elnidopicklepark.simplybook.me/v2/#",
  },
  {
    name: "The Dink Lab (24/7 pickleball center)",
    lat: 14.444269,
    lng: 120.903536,
    address: "3F, The Dink Lab (24/7 pickleball center), Robertson Plaza, Kawit, Cavite",
    city: "Kawit",
    country: "Philippines",
    hasLighting: true,
    phone: null,
    website: null,
  },
  {
    name: "The Pickleball Club - NOMO",
    lat: 14.459603,
    lng: 120.959817,
    address: "3rd floor, The Pickleball Club - NOMO, NOMO - A Vista Lifestyle Center, Bacoor Blvd, Bacoor, 4102 Cavite",
    city: "Bacoor",
    country: "Philippines",
    hasLighting: false,
    phone: "0968 879 6499",
    website: null,
  },
  {
    name: "Dink & Shot",
    lat: 14.633108,
    lng: 121.099354,
    address: "41 Majestic Subd, Marikina, 1807 Metro Manila",
    city: "Marikina",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "http://www.dinkandshot.com/",
  },
  {
    name: "Gameville Ball Park",
    lat: 14.577439,
    lng: 121.033897,
    address: "La Perla Building, Williams, Mandaluyong City, Metro Manila",
    city: "Mandaluyong City",
    country: "Philippines",
    hasLighting: false,
    phone: "0956 572 0008",
    website: null,
  },
  {
    name: "JY Pickleball Court",
    lat: 10.282124,
    lng: 124.785863,
    address: "San Vicente Ferrer, Matalom, 6526 Leyte",
    city: "Matalom",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Galingan Pickleball Court Hilongos",
    lat: 10.3733,
    lng: 124.748817,
    address: "9PMV W6Q Galingan Pickleball Court Hilongos, San Juan, Hilongos, Leyte",
    city: "Hilongos",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Dasmarinas Pickleball",
    lat: 14.31326,
    lng: 120.946669,
    address: "San Agustin II, Dasmariñas, Cavite",
    city: "Dasmariñas",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Met Park Sports Center",
    lat: 14.5437,
    lng: 120.99465,
    address: "Met Park, Metro Bank Ave, Pasay City, 1308",
    city: "Pasay City",
    country: "Philippines",
    hasLighting: false,
    phone: "0918 922 7687",
    website: "https://metpark.ph/sports-center/",
  },
  {
    name: "The Upper Deck Sports Center",
    lat: 14.560517,
    lng: 121.076434,
    address: "6/F, The Upper Deck Sports Center, Ortigas Technopoint Building, 1 Doña Julia Vargas Ave, Pasig, 1604 Metro Manila",
    city: "Pasig",
    country: "Philippines",
    hasLighting: false,
    phone: "0916 373 4428",
    website: "http://fb.com/TheUpperDeckPh",
  },
  {
    name: "Banay-Banay Pickleball",
    lat: 13.942088,
    lng: 121.138518,
    address: "W4M6 29M Banay-Banay Pickleball, Lipa City, Batangas",
    city: "Lipa City",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "The Pickle & Co. 1016",
    lat: 14.206022,
    lng: 121.15565,
    address: "Calamba, Laguna",
    city: "Calamba",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/share/1FdxgjgmMg/?mibextid=wwXIfr",
  },
  {
    name: "Ace & E Resort and A-Team Pickleball Lab.",
    lat: 14.17909,
    lng: 121.221791,
    address: "Block 5, Lot 8, Ace & E Resort and A-Team Pickleball Lab., Springdale Garden Subdivision, Victoria Street, Los Baños, 4030 Laguna",
    city: "Los Baños",
    country: "Philippines",
    hasLighting: false,
    phone: "0927 779 0255",
    website: "https://m.facebook.com/aceanderesort/",
  },
  { name: "Robinsons Palawan Pickleball Courts", lat: 9.74772, lng: 118.73472, address: "Robinsons Place Palawan, San Manuel, Puerto Princesa City, Palawan", city: "Puerto Princesa City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "PicklePoint Iloilo", lat: 10.706395, lng: 122.552497, address: "88 Sen. Benigno S. Aquino Jr. Ave, Mandurriao, Iloilo City, 5000 Iloilo", city: "Iloilo City", country: "Philippines", hasLighting: true, phone: null, website: "https://www.picklepointiloilo.com/" },
  { name: "Naga City Pickleball Club", lat: 13.62534, lng: 123.19324, address: "Elias Angeles St, Naga City, 4400 Camarines Sur", city: "Naga City", country: "Philippines", hasLighting: false, phone: null, website: "https://www.facebook.com/nagacitypickleballclub/" },
  { name: "Camp Ola Pickleball", lat: 13.146076, lng: 123.726621, address: "Camp Ola, Legazpi City, Albay", city: "Legazpi City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Kalamandarin Pickleball Court", lat: 15.484602, lng: 120.97578, address: "10 Assisi Street, Cabanatuan City, Nueva Ecija", city: "Cabanatuan City", country: "Philippines", hasLighting: false, phone: "0936 968 1008", website: null },
  { name: "Five-S Pickleball", lat: 15.603098, lng: 121.050811, address: "General Mamerto, Natividad, Nueva Ecija", city: "Natividad", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Bulacan Sports Complex", lat: 14.7948, lng: 120.87988, address: "School Road, MacArthur Highway, Malolos, Bulacan", city: "Malolos", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Butuan Pickleball Center", lat: 8.928231, lng: 125.551494, address: "Butuan City, Agusan del Norte", city: "Butuan City", country: "Philippines", hasLighting: false, phone: null, website: "https://butuanpickleballcenter.com/" },
  { name: "PickleZone Tagum", lat: 7.46077, lng: 125.784862, address: "Purok Dela Cruz, Brgy. Mankilam, Tagum City, Davao del Norte", city: "Tagum City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "ESJ Badminton Court", lat: 9.780521, lng: 118.730143, address: "Puerto Princesa City, Palawan", city: "Puerto Princesa City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "The Pickle Bloc", lat: 13.624012, lng: 123.185032, address: "Naga City, Camarines Sur", city: "Naga City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Smash Cab Badminton and Fitness", lat: 15.484602, lng: 120.97578, address: "Cabanatuan City, Nueva Ecija", city: "Cabanatuan City", country: "Philippines", hasLighting: true, phone: null, website: null },
  { name: "Smash Zone Caibaan", lat: 11.227464, lng: 125.027469, address: "6X4R+H6M, Tacloban Bypass Road, Tacloban City, Leyte", city: "Tacloban City", country: "Philippines", hasLighting: false, phone: "+63 956 316 6359", website: "http://www.supersaas.com/schedule/SmashZoneTac/Pickleball" },
  { name: "Smash Zone Southside", lat: 11.227464, lng: 125.027469, address: "6235+95J, Marasbaras, Tacloban City, 6500 Leyte", city: "Tacloban City", country: "Philippines", hasLighting: false, phone: "+63 945 855 0849", website: "http://www.supersaas.com/schedule/SmashZoneTac/Pickleball" },
  { name: "Smashville", lat: 11.227464, lng: 125.027469, address: "6265+Q52 Banezville, Bougainvilla, Tacloban City, Leyte", city: "Tacloban City", country: "Philippines", hasLighting: false, phone: null, website: "https://www.facebook.com/SmashVilleFitnessCenter/" },
  { name: "Triple Serve", lat: 11.227464, lng: 125.027469, address: "6X2R+PG7, Caibaan Rd, Tacloban City, Leyte", city: "Tacloban City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "SJ ProLine", lat: 11.227464, lng: 125.027469, address: "Airport Road, San Jose, Tacloban City, 6500 Leyte", city: "Tacloban City", country: "Philippines", hasLighting: false, phone: "+63 917 102 2781", website: null },
  { name: "Nitro Pickleyard", lat: 11.159448, lng: 124.990814, address: "5X8V+6PG, Palo, Leyte", city: "Palo", country: "Philippines", hasLighting: false, phone: null, website: "https://www.facebook.com/WilsonUyOfficial/" },
  { name: "The Pikol Farm", lat: 11.159448, lng: 124.990814, address: "5X4G+3M4, Gacao, Palo, Leyte", city: "Palo", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "G3K Backyard Pickleball", lat: 11.159448, lng: 124.990814, address: "Caloogan, along Palo West Bypass Road, Palo, Leyte", city: "Palo", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Vhits D.G Pickleball Court (Lighthouse)", lat: 11.159448, lng: 124.990814, address: "5X3W+QM6 Lighthouse of Brgy. Salvacion, Palo, Leyte", city: "Palo", country: "Philippines", hasLighting: true, phone: null, website: null },
  { name: "Ormoc's Uptown Pickle Yard (UPY)", lat: 11.009035, lng: 124.609394, address: "2JM4+GJ, Ormoc City, Leyte", city: "Ormoc City", country: "Philippines", hasLighting: false, phone: "+63 956 289 0530", website: "https://reclub.co/clubs/@ormocs-uptown-pickle-yard" },
  { name: "Picklers Garage", lat: 11.009035, lng: 124.609394, address: "3J52+7FM, Ormoc City, Leyte", city: "Ormoc City", country: "Philippines", hasLighting: false, phone: "+63 967 752 1289", website: "https://reclub.co" },
  { name: "Pickle Gym", lat: 11.009035, lng: 124.609394, address: "8WV9+9RR, Ormoc City, Leyte", city: "Ormoc City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "SM Center Ormoc (Pickleball)", lat: 11.009035, lng: 124.609394, address: "Real St, SM Center Ormoc, Ormoc City, 6541 Leyte", city: "Ormoc City", country: "Philippines", hasLighting: false, phone: null, website: "https://www.pickleheads.com/courts/ph/eastern-visayas/ormoc/sm-center-ormoc" },
  { name: "MarBingKoy's Pickleball Court", lat: 10.677802, lng: 124.797753, address: "PQ6X+P45, City of Baybay, Leyte", city: "Baybay City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "The Courtside Club", lat: 10.677802, lng: 124.797753, address: "Brgy. Santa Cruz, City of Baybay, 6521 Leyte", city: "Baybay City", country: "Philippines", hasLighting: false, phone: "+63 994 675 2201", website: null },
  { name: "The Pickle Camp", lat: 11.301745, lng: 124.687252, address: "6P78+X83, Carigara, Leyte", city: "Carigara", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Galingan Pickleball Court", lat: 10.3733, lng: 124.748817, address: "9PMV+W6Q, San Juan, Hilongos, Leyte", city: "Hilongos", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "10 Cases Pickleball Center", lat: 10.3733, lng: 124.748817, address: "9PFX+8F4, Hilongos, Leyte", city: "Hilongos", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "SERV Pickleball Club", lat: 10.132506, lng: 124.838515, address: "Ruperto K. Kangleon St, Mambajao, Maasin, 6600 Southern Leyte", city: "Maasin City", country: "Philippines", hasLighting: false, phone: "+63 995 011 7233", website: null },
  { name: "Chicken Yard Pickleball Club", lat: 11.79794, lng: 124.919008, address: "Barangay No. 2, Jiabong, Samar", city: "Jiabong", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Pickle Farm", lat: 12.066963, lng: 124.594666, address: "3HFC+QG6, San Policarpo, Calbayog, Samar", city: "Calbayog City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Basketball/Pickle Ball Court", lat: 12.066963, lng: 124.594666, address: "3GFR+VJ4 Trinidad, Sabang, Calbayog, Samar", city: "Calbayog City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Catbalogan City Lawn Tennis Court", lat: 11.775331, lng: 124.883118, address: "QVGP+8CC, Catbalogan City Proper, Samar (behind Capitol)", city: "Catbalogan City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "South Line Pickleball", lat: 11.607985, lng: 125.432243, address: "Sabang South Covered Court, City of Borongan, Eastern Samar", city: "Borongan City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "The White House Pickleball Courts", lat: 12.499648, lng: 124.636477, address: "GJ68+GQF Daganas, Catarman, Northern Samar", city: "Catarman", country: "Philippines", hasLighting: false, phone: "+63 917 187 9994", website: null },
  { name: "Jethro Sports Center", lat: 14.685095, lng: 120.978001, address: "031 Tadeo, Valenzuela, 1441 Metro Manila", city: "Valenzuela", country: "Philippines", hasLighting: false, phone: "0915 216 3020", website: "https://jethro-sports-center-app.glide.page/" },
  { name: "Philippine Airlines Sports Center", lat: 14.5437, lng: 120.99465, address: "G2H4 7VQ Philippine Airlines Sports Center, Andrews Ave, Pasay City, Metro Manila", city: "Pasay City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Southern Lagro Lawn Tennis Club 1987", lat: 14.651055, lng: 121.048625, address: "248 Ascension Ave, Quezon City, 1100 Metro Manila", city: "Quezon City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Neopolitan Brittany Clubhouse", lat: 12.8028, lng: 121.79706, address: "P3G4 834 Neopolitan Brittany Clubhouse, Quezon City", city: "P3G4 834 Neopolitan Brittany Clubhouse", country: "Philippines", hasLighting: false, phone: "(02) 8461 3534", website: "https://m.facebook.com/NeopolitanBrittanyClubhouse/" },
  { name: "Quantum Clubhouse", lat: 14.480901, lng: 120.981786, address: "Concha Cruz Drive, corner Alabang–Zapote Rd, Las Piñas, 1742 Metro Manila", city: "Las Piñas", country: "Philippines", hasLighting: false, phone: "0917 153 3487", website: null },
  { name: "Centro Atletico Badminton (Power Up Climbing)", lat: 14.619484, lng: 121.051073, address: "North Road, cor West Rd, Cubao, Quezon City", city: "Cubao", country: "Philippines", hasLighting: false, phone: "(02) 3412 7480", website: null },
  { name: "St. Francis Covered Court", lat: 14.578016, lng: 121.116307, address: "28 Chess St, San Juan, Barangay, Cainta, 1900 Rizal", city: "Cainta", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Athlete Central", lat: 14.578016, lng: 121.116307, address: "OAX Complex, KM 22 Ortigas Ave Ext, Cainta, 1900 Rizal", city: "Cainta", country: "Philippines", hasLighting: true, phone: "0920 544 7531", website: "https://athletecentral.fit/v2/" },
  { name: "PDCC Pickleball Court", lat: 14.107844, lng: 121.14533, address: "35R4 HGC PDCC Pickleball Court, Plaza D Events Place, Sampalocan Rd, Santo Tomas, Batangas", city: "Santo Tomas", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Versa Unlimited PH", lat: 17.610802, lng: 121.710407, address: "St Stephen Street, Tuguegarao City", city: "St Stephen Street", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Game Changer sports facility", lat: 10.327418, lng: 123.942152, address: "8WVF 2J5 Game Changer sports facility, Hernan Cortes St, Banilad, Mandaue, 6014 Cebu", city: "Mandaue", country: "Philippines", hasLighting: false, phone: "0926 705 0494", website: null },
  { name: "Shuttle Master Badminton Center", lat: 14.577505, lng: 121.018365, address: "3005 H. Santos, Makati City, Metro Manila", city: "Makati City", country: "Philippines", hasLighting: false, phone: "0920 954 6267", website: null },
  { name: "Tara Court Badminton", lat: 14.621101, lng: 121.063496, address: "Metrolane Complex, P. Tuazon Boulevard, Tagumpay, Tagumpay, 1109 Quezon City, Metro Manila", city: "Quezon City", country: "Philippines", hasLighting: false, phone: "0969 645 6896", website: null },
  { name: "Rockwell Club Tennis Courts", lat: 14.556795, lng: 121.021123, address: "5/F Powerplant Mall, Poblacion, Makati, Kalakhang Maynila", city: "Makati", country: "Philippines", hasLighting: false, phone: "0917 712 9688", website: "http://www.therockwellclub.com/" },
  { name: "Arcovia Padel Club", lat: 14.577535, lng: 121.07609, address: "Arco de Emperador, Pasig, 1604 Metro Manila", city: "Pasig", country: "Philippines", hasLighting: false, phone: "0917 147 3187", website: "https://www.manilapadelclub.com/" },
  { name: "SH2 badminton and pickleball court", lat: 14.480901, lng: 120.981786, address: "CX6W XW3 SH2 badminton and pickleball court, General Del Pilar St, Las Piñas, 1747 Metro Manila", city: "Las Piñas", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Campetic Basketball Court", lat: 11.192063, lng: 124.788198, address: "5XMR JMG Campetic Basketball Court, Campetic Rd, Barangay Campetic, Palo City, 6501 Leyte", city: "Palo City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Quest Pickleball Courts", lat: 14.515137, lng: 121.238086, address: "H7J2 WGV Quest Pickleball Courts, Quest Adventure Camp, Morong, Rizal", city: "Morong", country: "Philippines", hasLighting: false, phone: "0968 533 2484", website: "http://www.facebook.com/QuestAdventureCamp" },
  { name: "Mega Badminton Center", lat: 16.682545, lng: 121.551155, address: "15 Purok 1, Patul, City of Santiago, Isabela", city: "City of Santiago", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Silang Badminton Center", lat: 14.261924, lng: 120.969364, address: "7195 Emilio Aguinaldo Hwy, Silang, 4118 Cavite", city: "Silang", country: "Philippines", hasLighting: false, phone: "0917 544 9999", website: "https://www.facebook.com/profile.php?id=100057624811771&mibextid=ZbWKwL" },
  { name: "Gran Plains Pickleball Center", lat: 10.691858, lng: 122.568854, address: "Gran Plains Subdivision, Jaro, Iloilo City, Iloilo", city: "Iloilo City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "The Playground Badminton Court", lat: 14.480901, lng: 120.981786, address: "C2G7 3VR The Playground Badminton Court, CRM Ave, Almanza Uno, Las Piñas, Metro Manila", city: "Las Piñas", country: "Philippines", hasLighting: false, phone: "(02) 8806 7529", website: null },
  { name: "Poblacion Covered Court - Makati City NCR", lat: 14.556795, lng: 121.021123, address: "H29J 4X8 Poblacion Covered Court - Makati City NCR, J. P. Rizal St, Makati City, 1210 Metro Manila", city: "Makati City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "ZENtro Sports and Events Place", lat: 14.949913, lng: 120.758804, address: "XR7Q 8HX ZENtro Sports and Events Place, Apalit, Pampanga", city: "Apalit", country: "Philippines", hasLighting: false, phone: "0931 128 4909", website: null },
  { name: "MB Fitness & Pickleball Ground", lat: 14.651055, lng: 121.048625, address: "P374 F88 MB Fitness & Pickleball Ground, N Labayani, Quezon City, Metro Manila", city: "Quezon City", country: "Philippines", hasLighting: false, phone: "0961 791 6651", website: "https://www.facebook.com/mbfitnessg/" },
  { name: "The Riverside Courts", lat: 9.354105, lng: 122.837043, address: "Negros South Road, Dumaguete City, 6200 Negros Oriental", city: "Dumaguete City", country: "Philippines", hasLighting: false, phone: "0917 627 7866", website: "http://www.judevco.com/" },
  { name: "U.P. Village Covered Court", lat: 14.651055, lng: 121.048625, address: "Pacita Building, Mapayapa, Diliman, Quezon City, Metro Manila", city: "Quezon City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Habagat Sports Center", lat: 11.708897, lng: 122.364023, address: "Bougainvilla Rd, Andagaw, Kalibo, 5600 Aklan", city: "Kalibo", country: "Philippines", hasLighting: false, phone: "0920 961 4962", website: null },
  { name: "The Soft Serve Café and Courts", lat: 9.189716, lng: 123.26577, address: "Dauin, 6217 Negros Oriental", city: "Dauin", country: "Philippines", hasLighting: false, phone: "0927 799 2391", website: "https://thesoftservecafeandcourts.trafft.com/" },
  { name: "Play Padel Outdoor Courts", lat: 14.573041, lng: 121.051889, address: "645 Sheridan, Mandaluyong City, 1550 Metro Manila", city: "Mandaluyong City", country: "Philippines", hasLighting: false, phone: null, website: null },
  { name: "Alset Pickleball", lat: 14.556795, lng: 121.021123, address: "101 paseo de roxas, cor dela costa, Makati City, 1229 Metro Manila", city: "Makati City", country: "Philippines", hasLighting: false, phone: "0917 537 7878", website: "https://www.alsetpickleball.ph/" },
  { name: "Higher Ground Sports and Lifestyle", lat: 14.671682, lng: 121.074548, address: "M37C QCC Higher Ground Sports and Lifestyle, Tandang Sora Ave, Matandang Balara, Quezon City", city: "Matandang Balara", country: "Philippines", hasLighting: false, phone: "0905 526 6595", website: "http://www.facebook.com/highergroundsportsandlifestyle" },
  { name: "G Court Siargao", lat: 9.90376, lng: 126.05074, address: "Tourism Rd, Catangnan, Siargao, 8419 Surigao del Norte", city: "Siargao", country: "Philippines", hasLighting: false, phone: "0905 565 9912", website: null },
  { name: "BUDZminton & Pickleball COURT", lat: 10.399849, lng: 123.998762, address: "Liloan, Cebu", city: "Liloan", country: "Philippines", hasLighting: false, phone: "0977 786 8842", website: null },
  { name: "BODEGA22 Sports Center - Dagupan", lat: 16.043181, lng: 120.334189, address: "1255 Judge Jose de Venecia Ext, Dagupan City, Pangasinan", city: "Dagupan City", country: "Philippines", hasLighting: false, phone: "0960 638 5377", website: "https://www.facebook.com/bodega22ph" },
  { name: "Epicenter Courts Davao - Pickleball & Badminton", lat: 7.085773, lng: 125.616083, address: "Across Police Station, 5 Buhangin-Cabantian-Indangan Rd, Buhangin, Davao City, 8000 Davao del Sur", city: "Davao City", country: "Philippines", hasLighting: false, phone: "0956 964 0611", website: "http://playepicenterdvo.com/" },
  { name: "B31G Badminton and Pickleball Court", lat: 10.328561, lng: 123.900885, address: "Cebu North Coastal Rd. Bankerohan, Consolacion, Philippines Consolacion, Cebu City, 6001 Cebu", city: "Cebu City", country: "Philippines", hasLighting: false, phone: "0917 136 5309", website: "https://www.facebook.com/B31Gbadminton" },
];
