// Real Philippine pickleball courts (crowd-sourced from public listings,
// geocoded via OpenStreetMap). Seeded as unverified, pending review.
// See docs/10-map-system.md.
export interface SeedCourt {
  name: string;
  lat: number;
  lng: number;
  address: string;
  city: string;
  country: string;
  hasLighting: boolean;
  phone: string | null;
  website: string | null;
}

export const PH_COURTS: SeedCourt[] = [
  {
    name: "Wrong House Pickleball Court",
    lat: 11.005116,
    lng: 124.602292,
    address: "Purok 4, Brgy. Simangan, Ormoc City, 6541 Leyte",
    city: "Ormoc City",
    country: "Philippines",
    hasLighting: false,
    phone: "0999 883 1170",
    website: "https://www.facebook.com/profile.php?id=61573153073914",
  },
  {
    name: "Ace Pickleball Hub",
    lat: 11.001444,
    lng: 124.606216,
    address: "Pag-ibig Subd, Ormoc City, 6541 Leyte",
    city: "Ormoc City",
    country: "Philippines",
    hasLighting: false,
    phone: "0917 688 8874",
    website: null,
  },
  {
    name: "ServNdink Pickleball Court",
    lat: 11.068087,
    lng: 124.377987,
    address: "Sitio Bituon, San Juan, Palompon, 6538 Leyte",
    city: "Palompon",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: null,
  },
  {
    name: "Waypoint Pickleball Court",
    lat: 11.1045,
    lng: 124.4008,
    address: "Lomonon, Palompon, Leyte",
    city: "Palompon",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/share/14Rk5HptvtG/",
  },
  {
    name: "Smash Zone",
    lat: 11.242348,
    lng: 124.999928,
    address: "6245+2CG Tabuan National Hwy, Tacloban City, Leyte",
    city: "Tacloban City",
    country: "Philippines",
    hasLighting: false,
    phone: "0956 316 6359",
    website: "https://www.supersaas.com/schedule/SmashZoneTac/Pickleball",
  },
  {
    name: "Pampanga Pickleball Center",
    lat: 15.114283,
    lng: 120.608872,
    address: "Lot 2, Warehouse 1, Brgy. Telabastagan, San Fernando, 2000 Pampanga",
    city: "San Fernando",
    country: "Philippines",
    hasLighting: false,
    phone: "0908 989 2323",
    website: "https://pampanga-pickleball.rezerv.co/",
  },
  {
    name: "The Courtside Cebu",
    lat: 10.243608,
    lng: 123.844792,
    address: "N. Bacalso Ave, Starmall Talisay, 6045 Cebu",
    city: "Talisay",
    country: "Philippines",
    hasLighting: false,
    phone: "0930 392 0719",
    website: "https://thecourtsidecebu.com/",
  },
  {
    name: "The Pickle Yard Parañaque",
    lat: 14.490818,
    lng: 121.04337,
    address: "Km 15 West Service Road, SLEX, Parañaque, 1709 Metro Manila",
    city: "Parañaque",
    country: "Philippines",
    hasLighting: false,
    phone: "0936 959 5004",
    website: "https://www.facebook.com/profile.php?id=61567306075454",
  },
  {
    name: "24/7 Pickle Mandaluyong",
    lat: 14.578089,
    lng: 121.038922,
    address: "362 San Rafael St, Mandaluyong City, Metro Manila",
    city: "Mandaluyong City",
    country: "Philippines",
    hasLighting: true,
    phone: "0936 949 0815",
    website: "https://reclub.co/clubs/@24-7-pickle-mandaluyong",
  },
  {
    name: "Neopolitan Brittany Pickleball Courts",
    lat: 14.724751,
    lng: 121.054783,
    address: "Neopolitan Ave, Quezon City, Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: true,
    phone: "(02) 8461 3534",
    website: null,
  },
  {
    name: "Pickle Play",
    lat: 14.169878,
    lng: 120.921828,
    address: "Emerald 1, Crisanto M. De Los Reyes Ave, Amadeo, Cavite",
    city: "Amadeo",
    country: "Philippines",
    hasLighting: false,
    phone: "0927 355 8909",
    website: "https://facebook.com/pickleplayph",
  },
  {
    name: "Tierra Pickleball Club",
    lat: 14.674985,
    lng: 121.053448,
    address: "Tierra Verde, 2 Kalaw Ledesma Cir, Quezon City, 1116 Metro Manila",
    city: "Quezon City",
    country: "Philippines",
    hasLighting: false,
    phone: "0969 085 7204",
    website: "https://www.facebook.com/tierrapickleball",
  },
  {
    name: "Pickleball Central PH",
    lat: 15.134763,
    lng: 120.56727,
    address: "Fil-Am Friendship Hwy, Angeles, 2009 Pampanga",
    city: "Angeles",
    country: "Philippines",
    hasLighting: false,
    phone: "0908 891 1206",
    website: null,
  },
  {
    name: "Zone Sports Center",
    lat: 14.549852,
    lng: 121.030256,
    address: "7224 Sen. Gil J. Puyat Ave, Makati City, Metro Manila",
    city: "Makati City",
    country: "Philippines",
    hasLighting: false,
    phone: "0945 204 3013",
    website: "https://bit.ly/thezoneph",
  },
  {
    name: "PEDCI Pickleball Courts",
    lat: 14.583986,
    lng: 121.112543,
    address: "Village East Executive Homes, Sto. Domingo, Cainta, 1900 Rizal",
    city: "Cainta",
    country: "Philippines",
    hasLighting: true,
    phone: "0927 450 5978",
    website: "https://www.facebook.com/share/N1DMpYRhsNCpR55G/",
  },
  {
    name: "PickleballHub",
    lat: 14.422706,
    lng: 121.042081,
    address: "Km. 21 West Service Rd, Muntinlupa, Metro Manila",
    city: "Muntinlupa",
    country: "Philippines",
    hasLighting: false,
    phone: "0968 207 8876",
    website: "https://pickleballhubph.playbypoint.com/",
  },
  {
    name: "Davao Pickleball Court (Matina Town Square)",
    lat: 7.063788,
    lng: 125.596625,
    address: "Matina Town Square, Gen. Douglas MacArthur Hwy, Matina, Davao City",
    city: "Davao City",
    country: "Philippines",
    hasLighting: false,
    phone: "(082) 297 1780",
    website: "https://jfmdevelopmentcorp.com/pickleball",
  },
  {
    name: "Manila Pickleball Club (MPC)",
    lat: 14.570039,
    lng: 120.991526,
    address: "Malate, Manila, Metro Manila",
    city: "Manila",
    country: "Philippines",
    hasLighting: false,
    phone: null,
    website: "https://www.facebook.com/share/g/12BufEeWdwP/",
  },
  {
    name: "Powerhouse Pickleball and Badminton Center",
    lat: 14.250247,
    lng: 120.975527,
    address: "Km 39 Emilio Aguinaldo Hwy, Biga, Silang, 4118 Cavite",
    city: "Silang",
    country: "Philippines",
    hasLighting: true,
    phone: "0916 634 7024",
    website: "https://www.facebook.com/share/1BosxYBzoS/",
  },
];
